/* Modified based on the content generated by GitHub Copilot */

#include <stdio.h>
#include "safer_integer_short_macros.h"

void test_sum_of_series(int n) {
    int sum = 0;
    for (int i = 1; i <= n; ++i) {
        sum = diadd(sum, i); // debug mode add
    }
    printf("Sum of 1..%d = %d\n", n, sum);
}

void test_factorial(int n) {
    int result = 1;
    for (int i = 2; i <= n; ++i) {
        result = dimul(result, i); // debug mode multiply
    }
    printf("Factorial of %d = %d\n", n, result);
}

int test_power(int base, int exponent) {
    int result = 1;
    for (int i = 0; i < exponent; ++i) {
        result = dimul(result, base); // debug mode multiply
    }
    printf("%d ^ %d = %d\n", base, exponent, result);
    return result;
}

int test_binary_search(const int *arr, int size, int target) {
    int left = 0, right = size - 1;
    while (left <= right) {
        int mid = diadd(left, didiv(disub(right, left), 2)); // debug mode add/sub/div
        if (arr[mid] == target) {
            return mid;
        } else if (arr[mid] < target) {
            left = diadd(mid, 1);
        } else {
            right = disub(mid, 1);
        }
    }
    return -1;
}

void test_integer_overflow(void) {
    int a = INT_MAX;
    int b = 1;
    int result = diadd(a, b); // Should trigger overflow in debug mode
    printf("Overflow test: INT_MAX + 1 = %d\n", result);
}

void test_integer_underflow(void) {
    int a = INT_MIN;
    int b = 1;
    int result = disub(a, b); // Should trigger underflow in debug mode
    printf("Underflow test: INT_MIN - 1 = %d\n", result);
}

int main(void) {
    printf("Testing sum of series...\n");
    test_sum_of_series(100);

    printf("Testing factorial...\n");
    test_factorial(13); // 13! overflows 32-bit int

    printf("Testing integer power...\n");
    test_power(2, 31); // 2^31 overflows 32-bit int

    printf("Testing binary search...\n");
    int arr[10];
    for (int i = 0; i < 10; ++i) arr[i] = i * 3;
    int idx = test_binary_search(arr, 10, 9);
    printf("Binary search for 9 in arr: %s (index %d)\n", (idx >= 0 ? "found" : "not found"), idx);

    printf("Testing integer overflow...\n");
    test_integer_overflow();

    printf("Testing integer underflow...\n");
    test_integer_underflow();

    // You can add more tests for other types: int8_t, uint16_t, etc., using macros di8add, du16mul, etc.
    return 0;
}
